package com.lgj.dao;

import com.lgj.entity.Association1;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Association1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("orderId") String orderId, @Param("deliveryreceiptId") String deliveryreceiptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    int insert(Association1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table association_1
     *
     * @mbg.generated
     */
    List<Association1> selectAll();
}