package com.lgj.entity;

public class Association1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column association_1.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column association_1.deliveryReceipt_id
     *
     * @mbg.generated
     */
    private String deliveryreceiptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column association_1.order_id
     *
     * @return the value of association_1.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column association_1.order_id
     *
     * @param orderId the value for association_1.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column association_1.deliveryReceipt_id
     *
     * @return the value of association_1.deliveryReceipt_id
     *
     * @mbg.generated
     */
    public String getDeliveryreceiptId() {
        return deliveryreceiptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column association_1.deliveryReceipt_id
     *
     * @param deliveryreceiptId the value for association_1.deliveryReceipt_id
     *
     * @mbg.generated
     */
    public void setDeliveryreceiptId(String deliveryreceiptId) {
        this.deliveryreceiptId = deliveryreceiptId == null ? null : deliveryreceiptId.trim();
    }
}