package com.lgj.entity;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cul_id
     *
     * @mbg.generated
     */
    private String culId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_psd
     *
     * @mbg.generated
     */
    private String customerPsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_sex
     *
     * @mbg.generated
     */
    private String customerSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.brithday
     *
     * @mbg.generated
     */
    private Date brithday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cul_id
     *
     * @return the value of customer.cul_id
     *
     * @mbg.generated
     */
    public String getCulId() {
        return culId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cul_id
     *
     * @param culId the value for customer.cul_id
     *
     * @mbg.generated
     */
    public void setCulId(String culId) {
        this.culId = culId == null ? null : culId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_name
     *
     * @return the value of customer.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_name
     *
     * @param customerName the value for customer.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_psd
     *
     * @return the value of customer.customer_psd
     *
     * @mbg.generated
     */
    public String getCustomerPsd() {
        return customerPsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_psd
     *
     * @param customerPsd the value for customer.customer_psd
     *
     * @mbg.generated
     */
    public void setCustomerPsd(String customerPsd) {
        this.customerPsd = customerPsd == null ? null : customerPsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_sex
     *
     * @return the value of customer.customer_sex
     *
     * @mbg.generated
     */
    public String getCustomerSex() {
        return customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_sex
     *
     * @param customerSex the value for customer.customer_sex
     *
     * @mbg.generated
     */
    public void setCustomerSex(String customerSex) {
        this.customerSex = customerSex == null ? null : customerSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.brithday
     *
     * @return the value of customer.brithday
     *
     * @mbg.generated
     */
    public Date getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.brithday
     *
     * @param brithday the value for customer.brithday
     *
     * @mbg.generated
     */
    public void setBrithday(Date brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.tel
     *
     * @return the value of customer.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.tel
     *
     * @param tel the value for customer.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address
     *
     * @return the value of customer.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address
     *
     * @param address the value for customer.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.Comment
     *
     * @return the value of customer.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.Comment
     *
     * @param comment the value for customer.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}