package com.lgj.entity;

public class Deliveryplace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dep_id
     *
     * @mbg.generated
     */
    private String depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.mgl_id
     *
     * @mbg.generated
     */
    private String mglId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dep_name
     *
     * @mbg.generated
     */
    private String depName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.province_name
     *
     * @mbg.generated
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.mg_name
     *
     * @mbg.generated
     */
    private String mgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dep_tel
     *
     * @mbg.generated
     */
    private String depTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dep_addr
     *
     * @mbg.generated
     */
    private String depAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dep_id
     *
     * @return the value of deliveryplace.dep_id
     *
     * @mbg.generated
     */
    public String getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dep_id
     *
     * @param depId the value for deliveryplace.dep_id
     *
     * @mbg.generated
     */
    public void setDepId(String depId) {
        this.depId = depId == null ? null : depId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.mgl_id
     *
     * @return the value of deliveryplace.mgl_id
     *
     * @mbg.generated
     */
    public String getMglId() {
        return mglId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.mgl_id
     *
     * @param mglId the value for deliveryplace.mgl_id
     *
     * @mbg.generated
     */
    public void setMglId(String mglId) {
        this.mglId = mglId == null ? null : mglId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dep_name
     *
     * @return the value of deliveryplace.dep_name
     *
     * @mbg.generated
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dep_name
     *
     * @param depName the value for deliveryplace.dep_name
     *
     * @mbg.generated
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.province_name
     *
     * @return the value of deliveryplace.province_name
     *
     * @mbg.generated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.province_name
     *
     * @param provinceName the value for deliveryplace.province_name
     *
     * @mbg.generated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.city_name
     *
     * @return the value of deliveryplace.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.city_name
     *
     * @param cityName the value for deliveryplace.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.mg_name
     *
     * @return the value of deliveryplace.mg_name
     *
     * @mbg.generated
     */
    public String getMgName() {
        return mgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.mg_name
     *
     * @param mgName the value for deliveryplace.mg_name
     *
     * @mbg.generated
     */
    public void setMgName(String mgName) {
        this.mgName = mgName == null ? null : mgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dep_tel
     *
     * @return the value of deliveryplace.dep_tel
     *
     * @mbg.generated
     */
    public String getDepTel() {
        return depTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dep_tel
     *
     * @param depTel the value for deliveryplace.dep_tel
     *
     * @mbg.generated
     */
    public void setDepTel(String depTel) {
        this.depTel = depTel == null ? null : depTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dep_addr
     *
     * @return the value of deliveryplace.dep_addr
     *
     * @mbg.generated
     */
    public String getDepAddr() {
        return depAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dep_addr
     *
     * @param depAddr the value for deliveryplace.dep_addr
     *
     * @mbg.generated
     */
    public void setDepAddr(String depAddr) {
        this.depAddr = depAddr == null ? null : depAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.Comment
     *
     * @return the value of deliveryplace.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.Comment
     *
     * @param comment the value for deliveryplace.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}