package com.lgj.entity;

import java.util.Date;

public class Deliveryreceipt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.deliveryReceipt_id
     *
     * @mbg.generated
     */
    private String deliveryreceiptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.start_city
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.end_city
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.mid_city
     *
     * @mbg.generated
     */
    private String midCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.make_date
     *
     * @mbg.generated
     */
    private Date makeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.deliveryReceipt_id
     *
     * @return the value of deliveryreceipt.deliveryReceipt_id
     *
     * @mbg.generated
     */
    public String getDeliveryreceiptId() {
        return deliveryreceiptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.deliveryReceipt_id
     *
     * @param deliveryreceiptId the value for deliveryreceipt.deliveryReceipt_id
     *
     * @mbg.generated
     */
    public void setDeliveryreceiptId(String deliveryreceiptId) {
        this.deliveryreceiptId = deliveryreceiptId == null ? null : deliveryreceiptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.start_city
     *
     * @return the value of deliveryreceipt.start_city
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.start_city
     *
     * @param startCity the value for deliveryreceipt.start_city
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.end_city
     *
     * @return the value of deliveryreceipt.end_city
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.end_city
     *
     * @param endCity the value for deliveryreceipt.end_city
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.mid_city
     *
     * @return the value of deliveryreceipt.mid_city
     *
     * @mbg.generated
     */
    public String getMidCity() {
        return midCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.mid_city
     *
     * @param midCity the value for deliveryreceipt.mid_city
     *
     * @mbg.generated
     */
    public void setMidCity(String midCity) {
        this.midCity = midCity == null ? null : midCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.make_date
     *
     * @return the value of deliveryreceipt.make_date
     *
     * @mbg.generated
     */
    public Date getMakeDate() {
        return makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.make_date
     *
     * @param makeDate the value for deliveryreceipt.make_date
     *
     * @mbg.generated
     */
    public void setMakeDate(Date makeDate) {
        this.makeDate = makeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.state
     *
     * @return the value of deliveryreceipt.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.state
     *
     * @param state the value for deliveryreceipt.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.Comment
     *
     * @return the value of deliveryreceipt.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.Comment
     *
     * @param comment the value for deliveryreceipt.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}