package com.lgj.entity;

import java.math.BigDecimal;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.car_id
     *
     * @mbg.generated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.cul_id
     *
     * @mbg.generated
     */
    private String culId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.post_pname
     *
     * @mbg.generated
     */
    private String postPname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.post_ptel
     *
     * @mbg.generated
     */
    private String postPtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.post_addr
     *
     * @mbg.generated
     */
    private String postAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.get_pname
     *
     * @mbg.generated
     */
    private String getPname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.get_ptel
     *
     * @mbg.generated
     */
    private String getPtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.get_addr
     *
     * @mbg.generated
     */
    private String getAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_weight
     *
     * @mbg.generated
     */
    private Integer goodsWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_type
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_state
     *
     * @mbg.generated
     */
    private String orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.trans_post_price
     *
     * @mbg.generated
     */
    private BigDecimal transPostPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.delivery_price
     *
     * @mbg.generated
     */
    private BigDecimal deliveryPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_price
     *
     * @mbg.generated
     */
    private String totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_id
     *
     * @return the value of order.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_id
     *
     * @param orderId the value for order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.car_id
     *
     * @return the value of order.car_id
     *
     * @mbg.generated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.car_id
     *
     * @param carId the value for order.car_id
     *
     * @mbg.generated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.cul_id
     *
     * @return the value of order.cul_id
     *
     * @mbg.generated
     */
    public String getCulId() {
        return culId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.cul_id
     *
     * @param culId the value for order.cul_id
     *
     * @mbg.generated
     */
    public void setCulId(String culId) {
        this.culId = culId == null ? null : culId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.post_pname
     *
     * @return the value of order.post_pname
     *
     * @mbg.generated
     */
    public String getPostPname() {
        return postPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.post_pname
     *
     * @param postPname the value for order.post_pname
     *
     * @mbg.generated
     */
    public void setPostPname(String postPname) {
        this.postPname = postPname == null ? null : postPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.post_ptel
     *
     * @return the value of order.post_ptel
     *
     * @mbg.generated
     */
    public String getPostPtel() {
        return postPtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.post_ptel
     *
     * @param postPtel the value for order.post_ptel
     *
     * @mbg.generated
     */
    public void setPostPtel(String postPtel) {
        this.postPtel = postPtel == null ? null : postPtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.post_addr
     *
     * @return the value of order.post_addr
     *
     * @mbg.generated
     */
    public String getPostAddr() {
        return postAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.post_addr
     *
     * @param postAddr the value for order.post_addr
     *
     * @mbg.generated
     */
    public void setPostAddr(String postAddr) {
        this.postAddr = postAddr == null ? null : postAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.get_pname
     *
     * @return the value of order.get_pname
     *
     * @mbg.generated
     */
    public String getGetPname() {
        return getPname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.get_pname
     *
     * @param getPname the value for order.get_pname
     *
     * @mbg.generated
     */
    public void setGetPname(String getPname) {
        this.getPname = getPname == null ? null : getPname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.get_ptel
     *
     * @return the value of order.get_ptel
     *
     * @mbg.generated
     */
    public String getGetPtel() {
        return getPtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.get_ptel
     *
     * @param getPtel the value for order.get_ptel
     *
     * @mbg.generated
     */
    public void setGetPtel(String getPtel) {
        this.getPtel = getPtel == null ? null : getPtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.get_addr
     *
     * @return the value of order.get_addr
     *
     * @mbg.generated
     */
    public String getGetAddr() {
        return getAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.get_addr
     *
     * @param getAddr the value for order.get_addr
     *
     * @mbg.generated
     */
    public void setGetAddr(String getAddr) {
        this.getAddr = getAddr == null ? null : getAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_name
     *
     * @return the value of order.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_name
     *
     * @param goodsName the value for order.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_weight
     *
     * @return the value of order.goods_weight
     *
     * @mbg.generated
     */
    public Integer getGoodsWeight() {
        return goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_weight
     *
     * @param goodsWeight the value for order.goods_weight
     *
     * @mbg.generated
     */
    public void setGoodsWeight(Integer goodsWeight) {
        this.goodsWeight = goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_type
     *
     * @return the value of order.order_type
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_type
     *
     * @param orderType the value for order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_state
     *
     * @return the value of order.order_state
     *
     * @mbg.generated
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_state
     *
     * @param orderState the value for order.order_state
     *
     * @mbg.generated
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState == null ? null : orderState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.trans_post_price
     *
     * @return the value of order.trans_post_price
     *
     * @mbg.generated
     */
    public BigDecimal getTransPostPrice() {
        return transPostPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.trans_post_price
     *
     * @param transPostPrice the value for order.trans_post_price
     *
     * @mbg.generated
     */
    public void setTransPostPrice(BigDecimal transPostPrice) {
        this.transPostPrice = transPostPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.delivery_price
     *
     * @return the value of order.delivery_price
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryPrice() {
        return deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.delivery_price
     *
     * @param deliveryPrice the value for order.delivery_price
     *
     * @mbg.generated
     */
    public void setDeliveryPrice(BigDecimal deliveryPrice) {
        this.deliveryPrice = deliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.total_price
     *
     * @return the value of order.total_price
     *
     * @mbg.generated
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.total_price
     *
     * @param totalPrice the value for order.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.Comment
     *
     * @return the value of order.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.Comment
     *
     * @param comment the value for order.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}